# Generated by Django 3.1.2 on 2020-10-23 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0003_auto_20201022_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('item1', models.CharField(max_length=255)),
                ('item2', models.CharField(max_length=255)),
                ('item3', models.CharField(max_length=255)),
                ('item4', models.CharField(max_length=255)),
                ('item5', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
