# Generated by Django 3.1.2 on 2020-10-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='usuario',
        ),
    ]
