# Generated by Django 3.1.2 on 2020-11-28 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20201022_1115'),
        ('listas', '0002_remove_lista_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
