# Generated by Django 3.1.2 on 2020-10-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('data_aniversario', models.DateField()),
            ],
        ),
    ]
